### ISSUE TITLE
Add Transformer clean-up to deploy

### ISSUE THREAD

**Issue by notABluesSinger** [holidayextras/plugin-transformer#13]
When upgrading to [Transformer v5.1.0](https://github.com/holidayextras/transformer/releases/tag/v5.1.0) we need to ensure that the transient folder that is created during the testing process ran by the CI is cleared away before deployment.

If this folder exists the deployment will fail and we should not be transferring transformer database data from CI (which potentially contains test data) into a production environment.

This can easily be achieved by adding an extra command to the `circle.yml`;
```
test:
  ...
  post:
    ...
    - rm -rf transformer transformer-mr*
```

**Comment by hxpaul** [comment]
addressed https://github.com/holidayextras/plugin-transformer/pull/14
